version: '3'

services:

        nginx:
                build:
                        context: nginx
                container_name: nginx
                entrypoint: dockerize -wait tcp://node:3000 -timeout 10s nginx -g 'daemon off;'
                networks:
                        - nginx-node-network
                tty: true
                ports:
                        - "8080:80"
                depends_on:
                        - node

        node:
                build:
                        context: node
                container_name: node
                entrypoint: dockerize -wait tcp://db:3306 -timeout 10s docker-entrypoint.sh
                command: bash -c "node index.js"
                networks:
                        - nginx-node-network
                tty: true
                depends_on:
                        - db

        db:
                image: mysql:5.7
                command: --innodb-use-native-aio=0
                container_name: db
                restart: always
                tty: true
                environment: 
                        - MYSQL_DATABASE=nodedb
                        - MYSQL_ROOT_PASSWORD=root
                networks:
                        - nginx-node-network

networks:
        nginx-node-network:
                driver: bridge
